apiVersion: v1
kind:       Service
metadata:
  name: k8-end-service
  labels:
    app: k8-end-service
spec:
  ports:
    - port:       9090
      targetPort: 9090
      nodePort:   30040
  selector:
    app: k8-end-deployment
  type: NodePort
---
apiVersion: v1
kind:       Service
metadata:
  name: k8-start-service
  labels:
    app: k8-start-service
spec:
  ports:
    - port:       8080
      targetPort: 8080
      nodePort:   30030
  selector:
    app: k8-start-deployment
  type: NodePort
